### PR TITLE
Fix a crash in `MIDISPORT::PrepareOutput()` when writing sysex data

### LINKED ISSUE #26: Driver crash when sending large sysex message
(Thanks very much for the work on getting this driver running again. The MIDISport 2x2 was probably the first MIDI device I got working on OS X, 20 years ago, and it's great to save it from the electronics graveyard.)

When I send a large sysex message through the MIDISport 2x2, via `MIDISendSysex()`, the driver is consistently crashing here:
```
Thread 4 Crashed:
0   libsystem_platform.dylib      	0x00007fff20379236 _platform_memmove$VARIANT$Haswell + 566
1   com.leighsmith.midi.driver.midisport	0x0000000107a42bba MIDISPORT::PrepareOutput(InterfaceState*, std::__1::list<WriteQueueElem, std::__1::allocator<WriteQueueElem> >&, unsigned char*, unsigned long*, unsigned char*, unsigned long*) + 324
2   com.leighsmith.midi.driver.midisport	0x0000000107a445fa InterfaceState::DoWrite() + 98
3   com.leighsmith.midi.driver.midisport	0x0000000107a446f8 InterfaceState::WriteCallback(void*, int, void*) + 50
4   com.apple.framework.IOKit     	0x00007fff22af26bb IODispatchCalloutFromCFMessage + 348
5   com.apple.CoreFoundation      	0x00007fff2045aa88 __CFMachPortPerform + 288
6   com.apple.CoreFoundation      	0x00007fff2042ea44 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
7   com.apple.CoreFoundation      	0x00007fff2042e925 __CFRunLoopDoSource1 + 619
8   com.apple.CoreFoundation      	0x00007fff2042cfaf __CFRunLoopRun + 2400
9   com.apple.CoreFoundation      	0x00007fff2042bf8c CFRunLoopRunSpecific + 563
10  com.apple.audio.midi.CoreMIDI 	0x00007fff34d7246d DriverIOThread::Run() + 49
11  com.apple.audio.midi.CoreMIDI 	0x00007fff34d724e2 XThread::RunHelper(void*) + 10
12  com.apple.audio.midi.CoreMIDI 	0x00007fff34d7365b CAPThread::Entry(CAPThread*) + 77
13  libsystem_pthread.dylib       	0x00007fff203368fc _pthread_start + 224
14  libsystem_pthread.dylib       	0x00007fff20332443 thread_start + 15
```

Full crash log: [MIDIServer_2021-10-16-213858_lite.crash.zip](https://github.com/leighsmith/midisport-macos/files/7358865/MIDIServer_2021-10-16-213858_lite.crash.zip)

Steps:
1. Running on Big Sur 11.6, Install the driver via MIDISPORTDriver-v1.2.0.pkg.  Plug in the MIDISport 2x2, etc.
2. Download and run [SysEx Librarian](https://www.snoize.com/sysexlibrarian/) (current version: 1.4.1). I'm the author.
3. Get a large sysex file like this one: [64KB.syx.zip](https://github.com/leighsmith/midisport-macos/files/7358876/64KB.syx.zip).
4. Unzip it and drag it into the SysEx Librarian window.
5. In the Destination pop-up menu, choose one of the MIDISport’s ports
6. Select the sysex file, then press the Play button.  Let it finish playing or cancel after a little while, doesn't matter.

Expected: 
The whole 64 KB sysex message is transmitted, and nothing bad happens.

Actual:
The MIDISport's Out LED goes on for less than a second, then off.  There's a MIDIServer crash in Console.
(SysEx Librarian also acts kind of erratically afterwards, triggered by the MIDIServer crash and restart, but that's my problem to solve.)

Something about this long sysex message seems to be triggering the crash. I didn’t see it with small sysex messages. Haven't worked out exactly how long is too long, yet.

### PR DESCRIPTION
**Pull request by krevis**
If a packet contained sysex data that was 3n + 1 bytes long (for instance, 256 = 3 * 85 + 1), the code didn't correctly handle the last byte. It calculated an incorrect length (-1) and crashed when passing that to `memcpy`.

Fixed by simplifying the code a bit -- it's clearer and easier to follow the pattern of the other cases, and fill in the bytes one by one, instead of calling `memcpy` and `memset` for 1 or 2 bytes.

Fixes #26.

### CODE REVIEW

**Comment by leighsmith** [comment]
Looks good to me.

**Comment by krevis** [comment]
Thanks!

**Comment by SynthiaPayne** [comment]
And like that it was done!

**Comment by ramytramit** [comment]
Thank you both for making this work!

**Pull request merged**
